#!/usr/bin/env node
/**
 * Regenerate crates/uniflo-core/data/pricing-snapshot.json — the price catalog embedded in
 * uniflo (see docs/decisions/ADR-0010-价格目录同步与费用口径.md).
 *
 *   node scripts/build-pricing.mjs [models.dev api.json] [LiteLLM json]
 *
 * Without arguments both files are downloaded (network: models.dev + GitHub raw). The output
 * keeps the upstream shapes, filtered to first-party vendors and to the fields uniflo reads,
 * so the Rust side parses the snapshot and a live sync with the same code
 * (`uniflo_core::pricing::catalog::{parse_models_dev, parse_litellm}`).
 */
import { readFileSync, writeFileSync } from 'node:fs'

const MODELS_DEV_URL = 'https://models.dev/api.json'
const LITELLM_URL = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'
// Mirrors catalog::FIRST_PARTY / LITELLM_PROVIDERS: official list prices only, no resellers.
const FIRST_PARTY = ['anthropic', 'openai', 'google', 'minimax', 'moonshotai', 'zai', 'deepseek', 'alibaba', 'xai', 'groq']
const LITELLM_PROVIDERS = ['anthropic', 'openai', 'gemini', 'minimax', 'moonshot', 'zai', 'deepseek', 'dashscope', 'xai', 'groq']
const LITELLM_MODES = ['chat', 'responses', 'completion']
const COST_KEYS = ['input', 'output', 'cache_read', 'cache_write', 'tiers', 'context_over_200k']
const LITELLM_KEY = /^(input_cost_per_token|output_cost_per_token|cache_read_input_token_cost|cache_creation_input_token_cost)(_above_\d+k_tokens)?$/

async function load(path, url) {
  if (path) return JSON.parse(readFileSync(path, 'utf8'))
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`)
  return res.json()
}

const pick = (obj, keys) => Object.fromEntries(keys.filter((k) => obj?.[k] !== undefined).map((k) => [k, obj[k]]))
const sortKeys = (obj) => Object.fromEntries(Object.keys(obj).sort().map((k) => [k, obj[k]]))
// Same comparison key as catalog::match_key: last path segment, lowercase, `4.5` == `4-5`.
const matchKey = (id) => id.split('/').pop().toLowerCase().replace(/(\d)\.(?=\d)/g, '$1-')

const [mdPath, llPath] = process.argv.slice(2)
const md = await load(mdPath, MODELS_DEV_URL)
const ll = await load(llPath, LITELLM_URL)

const modelsDev = {}
const covered = new Set()
for (const provider of FIRST_PARTY) {
  const models = {}
  for (const [id, m] of Object.entries(md[provider]?.models ?? {})) {
    if (typeof m?.cost?.input !== 'number' || typeof m?.cost?.output !== 'number') continue
    models[id] = { cost: pick(m.cost, COST_KEYS), limit: pick(m.limit, ['context', 'output']) }
    covered.add(matchKey(id))
  }
  if (Object.keys(models).length) modelsDev[provider] = { models: sortKeys(models) }
}

const litellm = {}
for (const [key, m] of Object.entries(ll)) {
  if (!LITELLM_PROVIDERS.includes(m?.litellm_provider)) continue
  if (m.mode && !LITELLM_MODES.includes(m.mode)) continue
  if (typeof m.input_cost_per_token !== 'number' || typeof m.output_cost_per_token !== 'number') continue
  if (covered.has(matchKey(key))) continue
  const kept = { litellm_provider: m.litellm_provider, ...(m.mode ? { mode: m.mode } : {}) }
  for (const k of Object.keys(m)) if (LITELLM_KEY.test(k) && typeof m[k] === 'number') kept[k] = m[k]
  for (const k of ['max_input_tokens', 'max_output_tokens']) if (typeof m[k] === 'number') kept[k] = m[k]
  litellm[key] = kept
}

const out = {
  generated_at: Date.now(),
  note: 'Generated by scripts/build-pricing.mjs; USD per million tokens (models.dev) or per token (LiteLLM). Do not edit by hand.',
  sources: { 'models.dev': modelsDev, litellm: sortKeys(litellm) },
}
const target = new URL('../crates/uniflo-core/data/pricing-snapshot.json', import.meta.url)
writeFileSync(target, `${JSON.stringify(out, null, 1)}\n`)
const n = Object.values(modelsDev).reduce((s, p) => s + Object.keys(p.models).length, 0)
console.log(`pricing snapshot: ${n} models.dev + ${Object.keys(litellm).length} LiteLLM entries`)
